### PR TITLE
cleanup improvements for better context awareness and crash avoidance

### PR DESCRIPTION
**Pull request by marcelblum**
This is primarily to fix the crashes described in #33, plus has some bonus items. I am inexperienced with c++ & napi development so please let me know if anything here is horribly wrong or goes against conventions I am ignorant of (apologies in advance!).

- adds static `destroy()` methods for all 3 library wrappers, called using `napi_add_env_cleanup_hook()`
- `destroy()` releases the module's `Napi::Persistent` references to the library wrapper constructors, which was causing crashes when attempting to reuse Audify within the same process under Electron's newer process model
- in the case of `RtAudioWrap`, `destroy()` also releases the `errorTsfn` pointer for RtAudio's error callback; this was causing crashes if an error callback was used with `openStream`. The only way I found to consistently avoid related crashes was to do `errorTsfn = nullptr` on exit. I don't fully understand why this would be necessary, but it works. 🤷‍♂️ 
- adds latest Electron & Node stable versions to package.json build scripts, and updates the `prebuild` and `prebuild-install` deps to slightly newer min versions required for building for Node >=18
- also adds "rtaudio" as a keyword in the package.json. It was bothering me that a search on npmjs.com for "rtaudio" does not bring up Audify as a result, given that Audify contains the only stable implementation of rtaudio in Node! Hope this increases the discoverability of this great powerful library!
- also fixes some minor but confusing code comment typos I came across

### CODE REVIEW

**Comment by marcelblum** [comment]
Hmm, I see the macOS build is failing in the automated check. Looks like maybe a Travis config issue, I don't think due to any problems in my committed code AFAICT?

**Comment by marcelblum** [comment]
FWIW I just tested building for all target versions on an Intel Mac and got no errors.

**Review by almoghamdani — APPROVED** [review]

**Comment by almoghamdani** [comment]
Hi, thanks for the fixes. I cleaned the code a-bit and rebased it over the changes I made in `master` and approved.
It will be released in the upcoming release.

Regarding the macOS CI failure, don't worry about it. I refactored the CI to GitHub-Actions and now it works great :)

**Comment by marcelblum** [comment]
Thank you! And thanks for taking care of the cleanup :)

**Pull request merged**
